version: '3.7'
services:
  python3.7-cpu:
    build: docker/python3.7-cpu
    volumes:
      - ./:$HOME
    working_dir: $HOME
    command: bash
  tensorboard:
    build: docker/tensorboard
    volumes:
      - ./runs:/logs
    working_dir: /logs
    ports:
      - 6006:6006
    environment:
      reload_interval: 2
      log_dir: /logs
    privileged: true